chore: exclude sqlalachemy>=2.0.22 temporarily
ref: https://github.com/kvesteri/sqlalchemy-utils/issues/719

there is some issue b/w sqla-utils and sqla==2.0.22 so excuding sqla>=2.0.22
for now.

`TypeError: __init__() missing 1 required positional argument: 'dispatch'`